# Build and deploy static website by GitSite

image: node:20

pages:
  script:
    # to run puppeteer:
    - apt-get update && apt-get install -y libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2
    - npm install gitsite-cli -g
    - gitsite-cli build -o public -v
  artifacts:
    paths:
      - public
